### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [KolpakovaAnastasia/project_three#1]
1. Баг: /home/gagarski/repos/students/RusCheckers
2. Используйте принятый в Джаве стиль именования всего. Почему в предыдущем проекте вы это делали, а сейчас - нет?
3. Разберитесь с видимостью полей. В джаве принято поля делать приватными и добавлять им геттеры/сеттеры
4. GUI в Java FX нельзя обновлять из разных потоков (см. Timer). Используйте корректные инструменты для обновления GUI из правильного потока.

**Comment by KolpakovaAnastasia** [comment]
1) первый комментарий вообще не поняла
2) код был приведен к стилю принятому в Java
3) с видимостью и геттерами/сеттерами разобралась
4) до четвертого комментария руки не дошли, разберусь через несколько часов

**Comment by KolpakovaAnastasia** [comment]
Наконец-то исправила ваше четвертое замечание, правда пришлось таймер по-другому реализовывать. Если кратко, то:
Раньше в отдельном потоке работал Timer, который вычислял время, представлял его в виде строки и потом эту строку вставлял в TextField - дисплей, который видит пользователь, и я меняла значение TextField не в главном потоке, а в потоке таймера
Сейчас: 
1. создаётся и запускается GameTimer
2. создаётся Timer и задача GameTimerTask, таймер запускается. После этого GameTimer "на своей волне" тихо ведет отсчет времени, а Timer каждую секунду выполняет задачу GameTimerTask, которая берет у GameTimer строку с текущим временем и вставляет её в TextField - дисплей таймера на экране
Надеюсь это подойдет. В коде все, что к таймеру относится закомменчено с префиксом GAME_TIMER

**Comment by gagarski** [comment]
> первый комментарий вообще не поняла

Не то скопировал, ловите видос: https://www.youtube.com/watch?v=SvCypkd787Y

> код был приведен к стилю принятому в Java

пока не везде

> Наконец-то исправила ваше четвертое замечание, правда пришлось таймер по-другому реализовывать. Если кратко, то:

`Timer` всё ещё запускает код в другом треде и проблема всё ещё осталась. На самом деле, проблема обновления GUI из другого треда достаточно распространённая. Попробуйте сформулировать запрос и загуглить. Будете совсем в тупике, спрашивайте, загуглю за вас.

**Comment by KolpakovaAnastasia** [comment]
1)насчет бага я в курсе,  ищу ошибку уже очень долго и не понимаю, где она и как исправить. Можно если не найду,  просто прописать этот баг в курсовой? 
2) не получилось найти решение проблемы с потоком. Уже третий день над этим думаю и гуглила много по этому поводу.

**Comment by gagarski** [comment]
> не получилось найти решение проблемы с потоком. Уже третий день над этим думаю и гуглила много по этому поводу.

https://docs.oracle.com/javase/8/javafx/api/javafx/application/Platform.html#runLater-java.lang.Runnable-

> Можно если не найду, просто прописать этот баг в курсовой?

Вообще, из-за этого бага г=играть в игру почти невозможно. Мне выиграть не удалось ни разу. И проявляется он почти всегда. Берите дебаггер и смотрите, что не так.

**Comment by KolpakovaAnastasia** [comment]
Итак, таймер исправила, вернулась к прежнему таймеру и исправляла уже его. Суть: благодаря Platform.runLater() обновление "дисплея" происходит в главном UI-потоке, как и нужно было. А  чтобы поток не зависал, задача добавляется в очередь главного потока. Задачи из очереди выполняются одна за другой, как только завершается предыдущая. (поэтому и название "runLater")
Вот и всё.
Насчет бага пока не разобралась, но я пытаюсь. Завтра экзамен, наверное, после него еще сяду с дебаггером тестить прогу.
P.S.  код привела к стилю, принятому в Java
